import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import { Toaster } from "react-hot-toast";
import Providers from "@/components/Providers";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700", "900", "100"],
});

export const metadata: Metadata = {
  title: "Travel Blog",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${roboto.className} overflow-x-hidden bg-light`}>
        <Providers>
        <Navbar />
        {children}
        <Footer />
        </Providers>
        <Toaster/>
      </body>
    </html>
  );
}
