import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/shared/Navbar";
import Footer from "@/shared/Footer";
import { Toaster } from "react-hot-toast";
import AuthContext from "@/context/AuthContext";
import getCurrentUser from "@/actions/getCurrentUser";
import { EdgeStoreProvider } from "@/lib/edgestore";
const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700", "900", "100"],
});

export const metadata: Metadata = {
  title: "Travel Blog",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getCurrentUser();
  return (
    <html lang="en">
      <body className={`${roboto.className} overflow-x-hidden bg-light`}>
        <AuthContext>
          <EdgeStoreProvider>
            <Navbar user={user as any} />
            {children}
            <Footer />
            <Toaster />
          </EdgeStoreProvider>
        </AuthContext>
      </body>
    </html>
  );
}
